# This is a basic workflow to help you get started with Actions

name: CI

on: [workflow_dispatch]

jobs:
  download:
    name: Download
    runs-on: ubuntu-latest
    steps:
    - name: Install Git 
      run: sudo apt-get update && sudo apt-get install -y git
    - name: Initialize Git repository 
      run: git init
    - name: Set user email and name
      run: git config user.email "censored" && git config user.name "censored"
    - name: Fetch main branch 
      run: git fetch origin main
    - name: Checkout main branch 
      run: git checkout main
    - name: Install HTTrack 
      run: sudo apt-get update && sudo apt-get install -y httrack
    - name: Install unzip 
      run: sudo apt-get update && sudo apt-get install -y unzip
    - name: Download websit
      run: sudo httrack https://www.githubstatus.com/ -O Website -%v
    - name: Unzip website
      run: sudo unzip Website.zip -d tmp
    - name: Move website to root directory 
      run: mv tmp/* .
    - name: Remove tmp directory
      run: rm -r tmp
    - name: Add changes to Git 
      run: git add .
    - name: Commit changes
      run: git commit -m "Downloaded and unzipped website"
    - name: Push changes to main branch
      run: git push origin main

